stages:
- lint-check
- check
- build

ansible-lint:
  stage: lint-check
  image: ahembree/ansible
  tags:
    - docker
  script:
    - ansible-lint -v *.yml
    - ansible-playbook --inventory inventory --connection local --syntax-check *.yml



check alma_8:
  stage: check
  tags:
    - alma8
    - virtualbox
  script:
    - ansible-playbook -i inventory --connection local hms-docker.yml --check

check ubuntu_18.04:
  stage: check
  tags:
    - ubuntu1804
    - virtualbox
  script:
    - ansible-playbook -i inventory --connection local hms-docker.yml --check

check ubuntu_20.04:
  stage: check
  tags:
    - ubuntu2004
    - virtualbox
  script:
    - ansible-playbook -i inventory --connection local hms-docker.yml --check



build alma_8:
  stage: build
  tags:
    - alma8
    - virtualbox
  script:
    - ansible-playbook -i inventory --connection local hms-docker.yml

build ubuntu_18.04:
  stage: build
  tags:
    - ubuntu1804
    - virtualbox
  script:
    - ansible-playbook -i inventory --connection local hms-docker.yml

build ubuntu_20.04:
  stage: build
  tags:
    - ubuntu2004
    - virtualbox
  script:
    - ansible-playbook -i inventory --connection local hms-docker.yml
