---
- name: Ensure authentik env
  template:
    src: authentik_env.j2
    dest: "{{ hms_docker_data_path }}/.env"
    mode: 0600
    owner: root
    group: root
    backup: yes
    force: no

- name: Ensure Outposts directory
  file:
    path: "{{ hms_docker_apps_path }}/authentik/outposts"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure authentik Outpost configs
  template:
    src: authentik_outpost.j2
    dest: "{{ hms_docker_apps_path }}/authentik/outposts/authentik-{{ item.key }}.outpost.yml"
    mode: 0644
  with_dict: "{{ hms_docker_container_map }}"
  when: 
    - item.value.enabled 
    - item.value.authentik is defined and item.value.authentik
    - item.value.authentik_provider_type is defined and item.value.authentik_provider_type == 'proxy'

- name: Ensure authentik Outpost configs for 4K containers
  template:
    src: authentik_outpost_4k.j2
    dest: "{{ hms_docker_apps_path }}/authentik/outposts/authentik-{{ item.key }}-{{ separate_4k_instances_suffix }}.outpost.yml"
    mode: 0644
  with_dict: "{{ hms_docker_container_map }}"
  when: 
    - item.value.enabled 
    - item.value.authentik is defined and item.value.authentik
    - item.key == 'sonarr' or item.key == 'radarr'
    - item.value.authentik_provider_type is defined and item.value.authentik_provider_type == 'proxy'
    - separate_4k_instances_enable is defined and separate_4k_instances_enable

#### if authentik_provision_config is defined and authentik_provision_config:
#### do the logic to configure providers, applications, etc
