- name: Generate Docker Compose files for Cloudflare
  when: cloudflare_ddns_enabled | default(false) or cloudflare_tunnel_enabled| default(false) 
  ansible.builtin.template:
    src: containers/cloudflare.yml.j2
    dest: "{{ compose_dir.dest | default(hms_docker_data_path + '/compose_files') }}/cloudflare.yml"
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    mode: 0644
    trim_blocks: yes
    lstrip_blocks: yes
  register: cloudflare_compose_file_path

- name: Generate Docker Compose files for Flaresolverr
  when: flaresolverr_enabled
  ansible.builtin.template:
    src: containers/flaresolverr.yml.j2
    dest: "{{ compose_dir.dest | default(hms_docker_data_path + '/compose_files') }}/flaresolverr.yml"
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    mode: 0644
    trim_blocks: yes
    lstrip_blocks: yes
  register: flaresolverr_compose_file_path

- name: Generate Docker Compose files for Authentik
  when: hmsdocker_authentik_enabled_globally
  ansible.builtin.template:
    src: containers/authentik.yml.j2
    dest: "{{ compose_dir.dest | default(hms_docker_data_path + '/compose_files') }}/authentik.yml"
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    mode: 0644
    trim_blocks: yes
    lstrip_blocks: yes
  register: authentik_compose_file_path
