- name: Generate Docker Compose files for include
  ansible.builtin.file:
    dest: "{{ hms_docker_data_path }}/compose_files"
    state: directory
    mode: 0755
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
  register: compose_dir

- name: Generate Docker Compose file for Maintainerr 
  when: hmsdocker_container_enabled_maintainerr
  ansible.builtin.template:
    src: containers/maintainerr.yml.j2
    dest: "{{ compose_dir.dest | default(hms_docker_data_path + '/compose_files') }}/maintainerr.yml"
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    mode: 0644
    trim_blocks: yes
    lstrip_blocks: yes
  register: maintainerr_compose_file

- name: Generate Docker Compose file for Unpackerr 
  when: hmsdocker_container_enabled_unpackerr
  ansible.builtin.template:
    src: containers/unpackerr.yml.j2
    dest: "{{ compose_dir.dest | default(hms_docker_data_path + '/compose_files') }}/unpackerr.yml"
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
    mode: 0644
    trim_blocks: yes
    lstrip_blocks: yes
  register: unpackerr_compose_file
