---
- name: Obtain public IP.
  ipify_facts:
  register: public_ip

- name: Ensure paths exists locally.
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ hms_docker_data_path }}"
    - "{{ hms_docker_apps_path }}"
    - "{{ hms_docker_mount_path }}"
    - "{{ hms_docker_media_path }}"
    - "{{ transmission_custom_download_path }}"
  when: item is defined and item != ''

- name: NAS base configuration tasks.
  include_tasks: "nas_{{ hms_docker_media_share_type | lower }}.yml"

- name: Ensure additional NAS configuration
  include_tasks: "nas_additional_{{ item.type | lower }}.yml"
  with_items: "{{ nas_client_remote_additional_paths }}"
  when:
    - nas_client_remote_additional_paths is defined
    - nas_client_use_additional_paths is defined and nas_client_use_additional_paths
  no_log: yes

- name: Ensure library folders.
  file:
    path: "{{ hms_docker_media_path }}/{{ item.folder_name }}"
    state: directory
  with_items: "{{ hms_docker_library_folders }}"

- name: Ensure container config directories exist.
  file:
    path: "{{ hms_docker_apps_path }}/{{ item.key }}/config"
    state: directory
  with_dict: "{{ hms_docker_container_map }}"
  when: item.value.directory and (item.value.enabled is defined and item.value.enabled)

- name: Ensure separate 4K container config directories exist if enabled.
  file:
    path: "{{ hms_docker_apps_path }}/{{ item.key }}-{{ separate_4k_instances_suffix }}/config"
    state: directory
  with_dict: "{{ hms_docker_container_map }}"
  when: 
    - item.value.directory
    - item.value.enabled is defined and item.value.enabled
    - item.key == 'sonarr' or item.key == 'radarr'
    - separate_4k_instances_enable is defined and separate_4k_instances_enable

- name: Ensure Traefik
  import_tasks: "traefik.yml"
  when: container_enabled_traefik

- name: Ensure Authentik
  import_tasks: "authentik.yml"
  when: ((container_enabled_authentik) or 
        (authentik_enabled)) and 
        (traefik_ssl_enabled)

- name: Ensure JBOPS if enabled
  git:
    repo: https://github.com/blacktwin/JBOPS
    clone: true
    dest: "{{ tautulli_jbops_install_path }}"
  diff: false
  when: tautulli_jbops_enabled

- name: Ensure env
  template:
    src: env.j2
    dest: "{{ hms_docker_data_path }}/.env"
    mode: 0600
    owner: root
    group: root
    backup: yes
    lstrip_blocks: yes
    trim_blocks: yes
  # no_log: true
  register: compose_env
  vars:
  - authentik_key: "{{ (slurped_key_data['content'] | b64decode) if slurped_key_data['content'] is defined else '### Will be obtained during full run ###' }}"
  - authentik_pgpass: "{{ (slurped_pg_pass_data['content'] | b64decode) if slurped_pg_pass_data['content'] is defined else '### Will be obtained during full run ###' }}"
  - authentik_pgu: "{{ authentik_old_pg_user if authentik_old_pg_user is defined and authentik_old_pg_user != '' else authentik_pg_user }}"
  - authentik_pgdb: "{{ authentik_old_pg_db if authentik_old_pg_db is defined and authentik_old_pg_db != '' else authentik_pg_db }}"

- name: Ensure docker-compose.yml file.
  template:
    src: docker-compose.yml.j2
    dest: "{{ hms_docker_data_path }}/docker-compose.yml"
    group: docker
    mode: 0644
    backup: yes
    lstrip_blocks: yes
    trim_blocks: yes

- name: Ensure containers defined in compose file.
  docker_compose:
    project_src: "{{ hms_docker_data_path }}"
    project_name: "{{ project_name }}"
    pull: "{{ container_pull_images_first }}"
    state: "{{ hms_docker_compose_container_state }}"
    remove_orphans: "{{ container_remove_orphans }}"
    env_file: "{{ compose_env.dest }}"
  when: not ansible_check_mode

- name: Ensure Transmission and VPN connection
  import_tasks: "transmission.yml"
  when: container_enabled_transmission
