---
- name: Ensure requirements file
  ansible.builtin.copy:
    src: requirements.txt
    dest: "{{ hms_docker_data_path }}/requirements.txt"
    mode: 0644
  register: cf_worker_req_file_dest

- name: Ensure pip is updated first
  ansible.builtin.pip:
    virtualenv: "{{ hms_docker_data_path }}/.venv"
    virtualenv_command: python3 -m venv
    name:
      - pip
    state: latest

- name: Ensure pip environment
  ansible.builtin.pip:
    requirements: "{{ cf_worker_req_file_dest.dest }}"
    virtualenv: "{{ hms_docker_data_path }}/.venv"
    virtualenv_command: python3 -m venv

- name: Ensure pkcs12 script
  ansible.builtin.copy:
    src: traefik_cert_convert.py
    dest: "{{ hms_docker_data_path }}"
    mode: 0700
    owner: "{{ container_uid }}"
    group: "{{ container_gid }}"
  register: cert_script

- name: Ensure cron job
  ansible.builtin.cron:
    name: hms-docker-plex-ssl
    user: root
    job: "{{ hms_docker_data_path }}/.venv/bin/python {{ cert_script.dest | default(hms_docker_data_path + '/traefik_cert_convert.py') }}"
    minute: 0
    hour: 5
