---
- name: restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ hms_docker_data_path }}"
    project_name: "{{ project_name }}"
    state: restarted
    remove_orphans: "{{ container_remove_orphans }}"
    services:
      - traefik
  when: not traefik_certs_dir.changed

- name: restart sabnzbd
  community.docker.docker_compose_v2:
    project_src: "{{ hms_docker_data_path }}"
    project_name: "{{ project_name }}"
    state: restarted
    remove_orphans: "{{ container_remove_orphans }}"
    services:
      - sabnzbd
