name: Deploy to GitHub Pages

on:
  push:
    #paths:
    #  - 'gen-docs/**'

jobs:
  build-and-deploy:
    name: Build and Deploy Docs
    concurrency: build-deploy-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: gen-docs/package-lock.json

      - name: Install dependencies
        run: |
          cd gen-docs
          npm install --frozen-lockfile

      - name: Build website
        run: |
          cd gen-docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          folder: gen-docs/build
