name: GitHub Actions Testing
run-name: ${{ github.actor }} test out actions
on:
  push:
    branches: [ gh-actions ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  Ubuntu22:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Install ansible
        run: |
          sudo apt install python3-pip
          sudo pip3 install ansible
      - name: Run playbook
        run: |
          sudo ansible-playbook -i inventory --connection local hms-docker.yml --diff --extra-vars "hms_docker_compose_container_state=absent hms_docker_container_map.transmission.enabled=no hms_docker_container_map.plex.enabled=no"
      # - name: Run playbook
      #   uses: dawidd6/action-ansible-playbook@v2
      #   with:
      #     # Required, playbook filepath
      #     playbook: hms-docker.yml
      #     # Optional, directory where playbooks live
      #     directory: ${{ github.workspace }}
      #     # Optional, galaxy requirements filepath
      #     # requirements: galaxy-requirements.yml

      #     # Optional, additional flags to pass to ansible-playbook
      #     options: |
      #       --inventory inventory
      #       --connection local
      #       --extra-vars "hms_docker_compose_container_state=absent hms_docker_container_map.transmission.enabled=no hms_docker_container_map.plex.enabled=no"
      #       --verbose

