name: Deployment Tests
run-name: Test Deployment
on:
  push:
  schedule:
    - cron:  '23 9 * * 0'

permissions:
  contents: read

jobs:
  Ubuntu_22:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install ansible make python3-pip

      - name: Ensure base playbook requirements
        run: |
          mkdir -p ./vars/custom
          cp vars/default/*.yml ./vars/custom
          mv ./vars/custom/main.yml ./vars/custom/main_custom.yml
          sudo make install-reqs

      - name: Run playbook
        run: >-
          sudo ansible-playbook
          -i inventory
          --connection local
          hms-docker.yml
          --diff
          --extra-vars "
          is_github_runner=yes
          container_expose_ports=yes
          hms_docker_plex_ssl_enabled=yes
          separate_4k_instances_enable=yes
          tautulli_include_jbops=yes
          traefik_security_hardening=yes
          authentik_enabled_globally=no
          flaresolverr_enabled=yes
          custom_scripts_enabled=yes
          monitoring_scripts_enabled=yes
          media_avail_script_enabled=yes
          container_enabled_tdarr=yes
          container_enabled_uptimekuma=yes
          "

      - name: Check containers
        run: |
          sleep 10
          sudo make verify-containers
