name: GitHub Actions Testing
run-name: Test OS Deployments
on:
  push:
    branches: [ gh-actions ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  Ubuntu22:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install ansible
      - name: Run playbook
        run: |
          sudo ansible-playbook -i inventory --connection local hms-docker.yml --diff --extra-vars "hms_docker_compose_container_state=absent hms_docker_container_map.transmission.enabled=no hms_docker_container_map.plex.enabled=no is_github_runner=yes"

  Ubuntu20:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install ansible
      - name: Run playbook
        run: |
          sudo ansible-playbook --verbose -i inventory --connection local hms-docker.yml --diff --extra-vars "hms_docker_compose_container_state=absent hms_docker_container_map.transmission.enabled=no hms_docker_container_map.plex.enabled=no is_github_runner=yes"
