---
- name: Run RHEL-based install.
  import_tasks: redhat.yml
  when: gpu_family_override | lower == "redhat"

- name: Run Debian-based install.
  import_tasks: debian.yml
  when: ansible_facts["os_family"] | lower == "debian"

- name: Ensure the nvidia-container-toolkit package
  package:
    name: nvidia-container-toolkit
    state: "{{ gpu_prereq_packages_state }}"

- name: Verify nvidia-container-runtime-hook is in $PATH
  shell: "which nvidia-container-runtime-hook"
  register: nvidia_container_runtime_hook_path
  changed_when: False

- name: Exit if nvidia-container-runtime-hook is not in $PATH
  fail:
    msg: "nvidia-container-runtime-hook not found in $PATH"
  when: nvidia_container_runtime_hook_path.rc != 0

- name: Register nvidia-container-toolkit with docker
  shell:
    cmd: "nvidia-ctk runtime configure --runtime=docker"
  notify:
    - restart docker

- name: Restart docker
  shell:
    cmd: "systemctl restart docker"

- name: Verify CUDA container works
  shell:
    cmd: "docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi"
  register: nvidia_gpu_test
  changed_when: False

- name: Exit if CUDA container fails
  fail:
    msg: "CUDA container failed to run"
  when: nvidia_gpu_test.rc != 0
